// Lightweight i18n for the app chrome (navigation + common controls).
// Page bodies fall back to English; this can be extended key-by-key.

export type Lang = { code: string; name: string; flag: string };

export const LANGS: Lang[] = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'pt', name: 'Português', flag: '🇧🇷' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'uk', name: 'Українська', flag: '🇺🇦' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
];

export const KEYS = [
  'nav.markets', 'nav.games', 'nav.leaderboard', 'nav.calendar',
  'nav.daily', 'nav.cases', 'nav.wheel', 'nav.vip', 'nav.invite',
  'nav.cashier', 'nav.profile', 'nav.mybets', 'nav.admin',
  'nav.help', 'nav.how', 'nav.terms', 'nav.responsible',
  'group.play', 'group.rewards', 'group.account', 'group.help',
  'common.signin', 'common.search', 'common.language',
] as const;

// Values are in the same order as KEYS.
const ROWS: Record<string, string[]> = {
  en: ['Markets', 'Games', 'Leaderboard', 'Calendar', 'Daily rewards', 'Mystery Cases', 'Daily wheel', 'VIP Club', 'Invite & earn 50%', 'Cashier', 'Profile', 'My bets', 'Admin', 'Help center', 'How it works', 'Terms of Use', 'Responsible Gaming', 'Play', 'Rewards', 'Account', 'Help', 'Sign in', 'Search markets…', 'Language'],
  es: ['Mercados', 'Juegos', 'Clasificación', 'Calendario', 'Recompensas diarias', 'Cajas misteriosas', 'Rueda diaria', 'Club VIP', 'Invita y gana 50%', 'Cajero', 'Perfil', 'Mis apuestas', 'Admin', 'Centro de ayuda', 'Cómo funciona', 'Términos de uso', 'Juego responsable', 'Jugar', 'Recompensas', 'Cuenta', 'Ayuda', 'Iniciar sesión', 'Buscar mercados…', 'Idioma'],
  pt: ['Mercados', 'Jogos', 'Classificação', 'Calendário', 'Recompensas diárias', 'Caixas misteriosas', 'Roleta diária', 'Clube VIP', 'Convide e ganhe 50%', 'Caixa', 'Perfil', 'Minhas apostas', 'Admin', 'Central de ajuda', 'Como funciona', 'Termos de uso', 'Jogo responsável', 'Jogar', 'Recompensas', 'Conta', 'Ajuda', 'Entrar', 'Buscar mercados…', 'Idioma'],
  fr: ['Marchés', 'Jeux', 'Classement', 'Calendrier', 'Récompenses quotidiennes', 'Coffres mystères', 'Roue quotidienne', 'Club VIP', 'Invitez et gagnez 50%', 'Caisse', 'Profil', 'Mes paris', 'Admin', "Centre d'aide", 'Comment ça marche', "Conditions d'utilisation", 'Jeu responsable', 'Jouer', 'Récompenses', 'Compte', 'Aide', 'Se connecter', 'Rechercher des marchés…', 'Langue'],
  de: ['Märkte', 'Spiele', 'Bestenliste', 'Kalender', 'Tägliche Belohnungen', 'Mystery-Boxen', 'Tägliches Rad', 'VIP-Club', 'Einladen & 50% verdienen', 'Kasse', 'Profil', 'Meine Wetten', 'Admin', 'Hilfecenter', "So funktioniert's", 'Nutzungsbedingungen', 'Verantwortungsvolles Spielen', 'Spielen', 'Belohnungen', 'Konto', 'Hilfe', 'Anmelden', 'Märkte suchen…', 'Sprache'],
  it: ['Mercati', 'Giochi', 'Classifica', 'Calendario', 'Premi giornalieri', 'Casse misteriose', 'Ruota giornaliera', 'Club VIP', 'Invita e guadagna 50%', 'Cassa', 'Profilo', 'Le mie scommesse', 'Admin', 'Centro assistenza', 'Come funziona', "Termini d'uso", 'Gioco responsabile', 'Gioca', 'Premi', 'Account', 'Aiuto', 'Accedi', 'Cerca mercati…', 'Lingua'],
  ru: ['Рынки', 'Игры', 'Лидеры', 'Календарь', 'Ежедневные награды', 'Кейсы', 'Колесо дня', 'VIP-клуб', 'Пригласить · 50%', 'Касса', 'Профиль', 'Мои ставки', 'Админ', 'Центр помощи', 'Как это работает', 'Условия', 'Ответственная игра', 'Играть', 'Награды', 'Аккаунт', 'Помощь', 'Войти', 'Поиск рынков…', 'Язык'],
  uk: ['Ринки', 'Ігри', 'Лідери', 'Календар', 'Щоденні нагороди', 'Кейси', 'Щоденне колесо', 'VIP-клуб', 'Запросити · 50%', 'Каса', 'Профіль', 'Мої ставки', 'Адмін', 'Довідковий центр', 'Як це працює', 'Умови', 'Відповідальна гра', 'Грати', 'Нагороди', 'Акаунт', 'Допомога', 'Увійти', 'Пошук ринків…', 'Мова'],
  pl: ['Rynki', 'Gry', 'Ranking', 'Kalendarz', 'Codzienne nagrody', 'Skrzynie', 'Koło dnia', 'Klub VIP', 'Zaproś i zarób 50%', 'Kasa', 'Profil', 'Moje zakłady', 'Admin', 'Centrum pomocy', 'Jak to działa', 'Regulamin', 'Odpowiedzialna gra', 'Graj', 'Nagrody', 'Konto', 'Pomoc', 'Zaloguj się', 'Szukaj rynków…', 'Język'],
  tr: ['Piyasalar', 'Oyunlar', 'Lider tablosu', 'Takvim', 'Günlük ödüller', 'Gizemli kasalar', 'Günlük çark', 'VIP Kulüp', 'Davet et & %50 kazan', 'Kasa', 'Profil', 'Bahislerim', 'Yönetici', 'Yardım merkezi', 'Nasıl çalışır', 'Kullanım şartları', 'Sorumlu oyun', 'Oyna', 'Ödüller', 'Hesap', 'Yardım', 'Giriş yap', 'Piyasa ara…', 'Dil'],
  vi: ['Thị trường', 'Trò chơi', 'Bảng xếp hạng', 'Lịch', 'Phần thưởng hằng ngày', 'Hộp bí ẩn', 'Vòng quay hằng ngày', 'Câu lạc bộ VIP', 'Mời & kiếm 50%', 'Quầy', 'Hồ sơ', 'Cược của tôi', 'Quản trị', 'Trung tâm trợ giúp', 'Cách hoạt động', 'Điều khoản', 'Chơi có trách nhiệm', 'Chơi', 'Phần thưởng', 'Tài khoản', 'Trợ giúp', 'Đăng nhập', 'Tìm thị trường…', 'Ngôn ngữ'],
  id: ['Pasar', 'Game', 'Papan peringkat', 'Kalender', 'Hadiah harian', 'Kotak misteri', 'Roda harian', 'Klub VIP', 'Undang & dapat 50%', 'Kasir', 'Profil', 'Taruhan saya', 'Admin', 'Pusat bantuan', 'Cara kerja', 'Ketentuan', 'Bermain bertanggung jawab', 'Main', 'Hadiah', 'Akun', 'Bantuan', 'Masuk', 'Cari pasar…', 'Bahasa'],
  zh: ['市场', '游戏', '排行榜', '日历', '每日奖励', '神秘宝箱', '每日转盘', 'VIP 俱乐部', '邀请赚 50%', '收银台', '个人资料', '我的下注', '管理', '帮助中心', '玩法说明', '使用条款', '理性游戏', '游戏', '奖励', '账户', '帮助', '登录', '搜索市场…', '语言'],
  ja: ['マーケット', 'ゲーム', 'ランキング', 'カレンダー', 'デイリー報酬', 'ミステリーケース', 'デイリーホイール', 'VIPクラブ', '招待して50%獲得', 'キャッシャー', 'プロフィール', 'マイベット', '管理', 'ヘルプセンター', '使い方', '利用規約', '責任あるゲーム', 'プレイ', '報酬', 'アカウント', 'ヘルプ', 'ログイン', 'マーケットを検索…', '言語'],
  ko: ['마켓', '게임', '리더보드', '캘린더', '일일 보상', '미스터리 박스', '일일 룰렛', 'VIP 클럽', '초대하고 50% 받기', '캐셔', '프로필', '내 베팅', '관리자', '도움말 센터', '이용 방법', '이용약관', '책임 게임', '플레이', '보상', '계정', '도움말', '로그인', '마켓 검색…', '언어'],
};

export const STRINGS: Record<string, Record<string, string>> = {};
for (const [code, vals] of Object.entries(ROWS)) {
  const map: Record<string, string> = {};
  KEYS.forEach((k, i) => { map[k] = vals[i] ?? k; });
  STRINGS[code] = map;
}

// ---------------------------------------------------------------------------
// Extra strings (page titles, taglines, common buttons). Add new keys here.
// Anything missing for a locale falls back to English automatically.
// ---------------------------------------------------------------------------
const EXTRA: Record<string, Record<string, string>> = {
  'help.title': { en: 'How can we help?', es: '¿Cómo podemos ayudarte?', pt: 'Como podemos ajudar?', fr: 'Comment pouvons-nous aider ?', de: 'Wie können wir helfen?', it: 'Come possiamo aiutarti?', ru: 'Чем помочь?', uk: 'Чим допомогти?', pl: 'Jak możemy pomóc?', tr: 'Nasıl yardımcı olabiliriz?', vi: 'Chúng tôi có thể giúp gì?', id: 'Ada yang bisa kami bantu?', zh: '需要什么帮助？', ja: 'どうされましたか？', ko: '무엇을 도와드릴까요?' },
  'help.sub': { en: 'Guides, answers and tips for getting the most out of FORTX.', es: 'Guías, respuestas y consejos para aprovechar FORTX al máximo.', pt: 'Guias, respostas e dicas para aproveitar o FORTX ao máximo.', fr: 'Guides, réponses et astuces pour profiter au mieux de FORTX.', de: 'Anleitungen, Antworten und Tipps für das Beste aus FORTX.', it: 'Guide, risposte e consigli per sfruttare al meglio FORTX.', ru: 'Гайды, ответы и советы, чтобы получить максимум от FORTX.', uk: 'Гайди, відповіді та поради, щоб отримати максимум від FORTX.', pl: 'Poradniki, odpowiedzi i wskazówki, jak najlepiej wykorzystać FORTX.', tr: "FORTX'ten en iyi şekilde yararlanmak için rehberler, yanıtlar ve ipuçları.", vi: 'Hướng dẫn, câu trả lời và mẹo để tận dụng tối đa FORTX.', id: 'Panduan, jawaban, dan tips untuk memaksimalkan FORTX.', zh: '指南、答案和技巧，助你充分利用 FORTX。', ja: 'FORTXを最大限に活用するためのガイド、回答、ヒント。', ko: 'FORTX를 최대한 활용하기 위한 가이드, 답변, 팁.' },
  'help.contactTitle': { en: 'Still need a hand?', es: '¿Aún necesitas ayuda?', pt: 'Ainda precisa de ajuda?', fr: 'Besoin d’aide ?', de: 'Brauchst du noch Hilfe?', it: 'Hai ancora bisogno di aiuto?', ru: 'Нужна помощь?', uk: 'Потрібна допомога?', pl: 'Potrzebujesz pomocy?', tr: 'Hâlâ yardım mı lazım?', vi: 'Vẫn cần trợ giúp?', id: 'Masih butuh bantuan?', zh: '仍需帮助？', ja: 'お困りですか？', ko: '도움이 필요하신가요?' },
  'help.contactBtn': { en: 'Contact us', es: 'Contáctanos', pt: 'Fale conosco', fr: 'Nous contacter', de: 'Kontaktiere uns', it: 'Contattaci', ru: 'Связаться с нами', uk: 'Зв’язатися з нами', pl: 'Skontaktuj się', tr: 'Bize ulaşın', vi: 'Liên hệ', id: 'Hubungi kami', zh: '联系我们', ja: 'お問い合わせ', ko: '문의하기' },
  'help.searchPlaceholder': { en: 'Search articles…', es: 'Buscar artículos…', pt: 'Buscar artigos…', fr: 'Rechercher des articles…', de: 'Artikel suchen…', it: 'Cerca articoli…', ru: 'Поиск статей…', uk: 'Пошук статей…', pl: 'Szukaj artykułów…', tr: 'Makale ara…', vi: 'Tìm bài viết…', id: 'Cari artikel…', zh: '搜索文章…', ja: '記事を検索…', ko: '도움말 검색…' },
  'wheel.title': { en: 'Daily Wheel of Fortune', es: 'Rueda de la Fortuna diaria', pt: 'Roleta da Sorte diária', fr: 'Roue de la Fortune quotidienne', de: 'Tägliches Glücksrad', it: 'Ruota della Fortuna giornaliera', ru: 'Колесо Фортуны', uk: 'Колесо Фортуни', pl: 'Codzienne Koło Fortuny', tr: 'Günlük Şans Çarkı', vi: 'Vòng quay May mắn hằng ngày', id: 'Roda Keberuntungan Harian', zh: '每日幸运转盘', ja: 'デイリー運命のホイール', ko: '데일리 행운의 룰렛' },
  'calendar.title': { en: 'Events calendar', es: 'Calendario de eventos', pt: 'Calendário de eventos', fr: 'Calendrier des événements', de: 'Veranstaltungskalender', it: 'Calendario eventi', ru: 'Календарь событий', uk: 'Календар подій', pl: 'Kalendarz wydarzeń', tr: 'Etkinlik takvimi', vi: 'Lịch sự kiện', id: 'Kalender acara', zh: '事件日历', ja: 'イベントカレンダー', ko: '이벤트 캘린더' },
  'calendar.sub': { en: 'Upcoming markets by close date — plan your predictions ahead.', es: 'Próximos mercados por fecha de cierre — planifica tus predicciones.', pt: 'Próximos mercados por data de fechamento — planeje suas previsões.', fr: 'Marchés à venir par date de clôture — planifiez vos prédictions.', de: 'Kommende Märkte nach Schlussdatum — plane deine Vorhersagen.', it: 'Mercati in arrivo per data di chiusura — pianifica le tue previsioni.', ru: 'Ближайшие рынки по дате закрытия — планируй прогнозы заранее.', uk: 'Майбутні ринки за датою закриття — плануйте прогнози заздалегідь.', pl: 'Nadchodzące rynki według daty zamknięcia — planuj swoje przewidywania z wyprzedzeniem.', tr: 'Kapanış tarihine göre yaklaşan piyasalar — tahminlerini önceden planla.', vi: 'Các thị trường sắp tới theo ngày đóng — lên kế hoạch dự đoán trước.', id: 'Pasar mendatang berdasarkan tanggal penutupan — rencanakan prediksi Anda lebih awal.', zh: '按截止日期排列的即将开放市场——提前规划你的预测。', ja: '締切日順の今後のマーケット — 予測を事前に計画しよう。', ko: '마감일순 예정 마켓 — 미리 예측을 계획하세요.' },
  'games.sub': { en: 'Provably-fair instant games. Pick one and play.', es: 'Juegos instantáneos con verificación justa. Elige y juega.', pt: 'Jogos instantâneos com prova de justiça. Escolha e jogue.', fr: 'Jeux instantanés vérifiables. Choisissez et jouez.', de: 'Beweisbar faire Sofortspiele. Wähle eines und spiele.', it: 'Giochi istantanei provabilmente equi. Scegli e gioca.', ru: 'Честные мгновенные игры. Выбирай и играй.', uk: 'Чесні миттєві ігри. Обирай і грай.', pl: 'Uczciwe gry natychmiastowe. Wybierz i graj.', tr: 'Kanıtlanabilir adil anlık oyunlar. Seç ve oyna.', vi: 'Trò chơi tức thì công bằng. Chọn và chơi.', id: 'Game instan yang terbukti adil. Pilih dan main.', zh: '可验证公平的即时游戏，选一个开玩。', ja: '実証可能に公平な即時ゲーム。選んでプレイ。', ko: '검증 가능한 공정 게임. 골라서 플레이하세요.' },
  'common.playNow': { en: 'Play now', es: 'Jugar ahora', pt: 'Jogar agora', fr: 'Jouer', de: 'Jetzt spielen', it: 'Gioca ora', ru: 'Играть', uk: 'Грати', pl: 'Graj teraz', tr: 'Şimdi oyna', vi: 'Chơi ngay', id: 'Main sekarang', zh: '立即游戏', ja: '今すぐプレイ', ko: '지금 플레이' },
  'common.signinToPlay': { en: 'Sign in to play', es: 'Inicia sesión para jugar', pt: 'Entre para jogar', fr: 'Connectez-vous pour jouer', de: 'Zum Spielen anmelden', it: 'Accedi per giocare', ru: 'Войдите, чтобы играть', uk: 'Увійдіть, щоб грати', pl: 'Zaloguj się, aby grać', tr: 'Oynamak için giriş yap', vi: 'Đăng nhập để chơi', id: 'Masuk untuk bermain', zh: '登录后游戏', ja: 'ログインしてプレイ', ko: '로그인하고 플레이' },
  'common.loading': { en: 'Loading…', es: 'Cargando…', pt: 'Carregando…', fr: 'Chargement…', de: 'Lädt…', it: 'Caricamento…', ru: 'Загрузка…', uk: 'Завантаження…', pl: 'Ładowanie…', tr: 'Yükleniyor…', vi: 'Đang tải…', id: 'Memuat…', zh: '加载中…', ja: '読み込み中…', ko: '불러오는 중…' },
  'common.copyLink': { en: 'Copy link', es: 'Copiar enlace', pt: 'Copiar link', fr: 'Copier le lien', de: 'Link kopieren', it: 'Copia link', ru: 'Копировать ссылку', uk: 'Копіювати посилання', pl: 'Kopiuj link', tr: 'Bağlantıyı kopyala', vi: 'Sao chép liên kết', id: 'Salin tautan', zh: '复制链接', ja: 'リンクをコピー', ko: '링크 복사' },
  'common.copied': { en: 'Copied!', es: '¡Copiado!', pt: 'Copiado!', fr: 'Copié !', de: 'Kopiert!', it: 'Copiato!', ru: 'Скопировано!', uk: 'Скопійовано!', pl: 'Skopiowano!', tr: 'Kopyalandı!', vi: 'Đã sao chép!', id: 'Disalin!', zh: '已复制！', ja: 'コピーしました！', ko: '복사됨!' },
  'common.spin': { en: 'Spin', es: 'Girar', pt: 'Girar', fr: 'Tourner', de: 'Drehen', it: 'Gira', ru: 'Крутить', uk: 'Крутити', pl: 'Zakręć', tr: 'Çevir', vi: 'Quay', id: 'Putar', zh: '旋转', ja: 'スピン', ko: '돌리기' },
  'common.claimToBalance': { en: 'Claim to balance', es: 'Reclamar al saldo', pt: 'Resgatar para o saldo', fr: 'Récupérer sur le solde', de: 'Auf Guthaben gutschreiben', it: 'Riscatta sul saldo', ru: 'Забрать на баланс', uk: 'Забрати на баланс', pl: 'Odbierz na saldo', tr: 'Bakiyeye aktar', vi: 'Nhận vào số dư', id: 'Klaim ke saldo', zh: '领取到余额', ja: '残高に受け取る', ko: '잔액으로 받기' },
  'home.casinoTitle': { en: 'Casino games', es: 'Juegos de casino', pt: 'Jogos de cassino', fr: 'Jeux de casino', de: 'Casino-Spiele', it: 'Giochi da casinò', ru: 'Игры казино', uk: 'Ігри казино', pl: 'Gry kasynowe', tr: 'Casino oyunları', vi: 'Trò chơi sòng bài', id: 'Permainan kasino', zh: '娱乐场游戏', ja: 'カジノゲーム', ko: '카지노 게임' },
  'games.mines': { en: 'Mines', es: 'Minas', pt: 'Minas', fr: 'Mines', de: 'Minen', it: 'Mine', ru: 'Мины', uk: 'Міни', pl: 'Miny', tr: 'Mayınlar', vi: 'Số mìn', id: 'Ranjau', zh: '扫雷', ja: '地雷', ko: '지뢰' },
  'games.crash': { en: 'Crash', es: 'Crash', pt: 'Crash', fr: 'Crash', de: 'Crash', it: 'Crash', ru: 'Краш', uk: 'Краш', pl: 'Crash', tr: 'Crash', vi: 'Crash', id: 'Crash', zh: '崩盘', ja: 'クラッシュ', ko: '크래시' },
  'games.tower': { en: 'Tower', es: 'Torre', pt: 'Torre', fr: 'Tour', de: 'Turm', it: 'Torre', ru: 'Башня', uk: 'Вежа', pl: 'Wieża', tr: 'Kule', vi: 'Tháp', id: 'Menara', zh: '塔楼', ja: 'タワー', ko: '타워' },
  'games.ladder': { en: 'Ladder', es: 'Escalera', pt: 'Escada', fr: 'Échelle', de: 'Leiter', it: 'Scala', ru: 'Лестница', uk: 'Драбина', pl: 'Drabina', tr: 'Merdiven', vi: 'Thang', id: 'Tangga', zh: '梯子', ja: 'ラダー', ko: '사다리' },

  'mines.title': { en: 'Mines', es: 'Minas', pt: 'Minas', fr: 'Mines', de: 'Minen', it: 'Mine', ru: 'Мины', uk: 'Міни', pl: 'Miny', tr: 'Mayınlar', vi: 'Số mìn', id: 'Ranjau', zh: '扫雷', ja: '地雷', ko: '지뢰' },
  'mines.subtitle': { en: 'Flip tiles for gems. Avoid the mines. Cash out before you hit one.', es: 'Voltea fichas para encontrar gemas. Evita las minas. Retira antes de tocar una.', pt: 'Vire as fichas em busca de gemas. Evite as minas. Saque antes de acertar uma.', fr: 'Retournez des cases pour trouver des gemmes. Évitez les mines. Encaissez avant d’en toucher une.', de: 'Decke Felder auf und finde Edelsteine. Meide die Minen. Zahl aus, bevor du eine triffst.', it: 'Scopri le caselle per trovare le gemme. Evita le mine. Incassa prima di colpirne una.', ru: 'Открывай клетки с самоцветами. Избегай мин. Забери выигрыш, пока не подорвался.', uk: 'Відкривай клітинки з самоцвітами. Уникай мін. Забери виграш, поки не підірвався.', pl: 'Odkrywaj kafelki z klejnotami. Unikaj min. Wypłać, zanim trafisz na minę.', tr: 'Değerli taş için karoları çevir. Mayınlardan kaçın. Birine çarpmadan önce nakde çevir.', vi: 'Lật ô để tìm đá quý. Tránh mìn. Rút tiền trước khi trúng mìn.', id: 'Buka ubin untuk mencari permata. Hindari ranjau. Cairkan sebelum kena ranjau.', zh: '翻开格子寻找宝石，躲开地雷，踩雷前及时兑现。', ja: 'タイルをめくって宝石を探そう。地雷を避け、当たる前にキャッシュアウト。', ko: '타일을 뒤집어 보석을 찾으세요. 지뢰를 피하고 터지기 전에 캐시아웃하세요.' },
  'mines.signInPrompt': { en: 'Sign in to play and claim $5 free.', es: 'Inicia sesión para jugar y reclama $5 gratis.', pt: 'Entre para jogar e resgate $5 grátis.', fr: 'Connectez-vous pour jouer et recevoir 5 $ gratuits.', de: 'Melde dich an, um zu spielen und 5 $ gratis zu erhalten.', it: 'Accedi per giocare e ricevi $5 gratis.', ru: 'Войдите, чтобы играть, и получите $5 бесплатно.', uk: 'Увійдіть, щоб грати, і отримайте $5 безкоштовно.', pl: 'Zaloguj się, aby grać i odbierz $5 gratis.', tr: 'Oynamak ve 5$ bedava kazanmak için giriş yap.', vi: 'Đăng nhập để chơi và nhận 5 đô miễn phí.', id: 'Masuk untuk bermain dan klaim $5 gratis.', zh: '登录即可游戏并领取 5 美元免费金。', ja: 'ログインしてプレイし、5ドル無料を受け取ろう。', ko: '로그인하고 플레이하면 무료 $5를 받을 수 있어요.' },
  'mines.youWon': { en: 'You won', es: 'Ganaste', pt: 'Você ganhou', fr: 'Vous avez gagné', de: 'Du hast gewonnen', it: 'Hai vinto', ru: 'Вы выиграли', uk: 'Ви виграли', pl: 'Wygrałeś', tr: 'Kazandın', vi: 'Bạn đã thắng', id: 'Anda menang', zh: '你赢了', ja: '勝ちました', ko: '승리했습니다' },
  'mines.boom': { en: 'Boom — you hit a mine', es: 'Boom — pisaste una mina', pt: 'Bum — você acertou uma mina', fr: 'Boum — vous avez touché une mine', de: 'Peng — du hast eine Mine getroffen', it: 'Boom — hai colpito una mina', ru: 'Бум — вы подорвались на мине', uk: 'Бум — ви підірвались на міні', pl: 'Bum — trafiłeś na minę', tr: 'Güm — bir mayına bastın', vi: 'Bùm — bạn đã trúng mìn', id: 'Duar — Anda kena ranjau', zh: '轰——你踩到地雷了', ja: 'ドカン — 地雷を踏みました', ko: '펑 — 지뢰를 밟았어요' },
  'mines.busted': { en: 'Busted', es: 'Perdiste', pt: 'Perdeu', fr: 'Perdu', de: 'Verloren', it: 'Perso', ru: 'Проигрыш', uk: 'Програш', pl: 'Przegrana', tr: 'Kaybettin', vi: 'Thua', id: 'Kalah', zh: '爆了', ja: '失敗', ko: '터짐' },
  'mines.playAgain': { en: 'Play again', es: 'Jugar de nuevo', pt: 'Jogar novamente', fr: 'Rejouer', de: 'Erneut spielen', it: 'Gioca ancora', ru: 'Играть снова', uk: 'Грати знову', pl: 'Zagraj ponownie', tr: 'Tekrar oyna', vi: 'Chơi lại', id: 'Main lagi', zh: '再玩一次', ja: 'もう一度プレイ', ko: '다시 플레이' },
  'mines.currentMultiplier': { en: 'Current multiplier', es: 'Multiplicador actual', pt: 'Multiplicador atual', fr: 'Multiplicateur actuel', de: 'Aktueller Multiplikator', it: 'Moltiplicatore attuale', ru: 'Текущий множитель', uk: 'Поточний множник', pl: 'Aktualny mnożnik', tr: 'Mevcut çarpan', vi: 'Hệ số hiện tại', id: 'Pengganda saat ini', zh: '当前倍数', ja: '現在の倍率', ko: '현재 배율' },
  'mines.nextTile': { en: 'next tile', es: 'próxima casilla', pt: 'próxima casa', fr: 'case suivante', de: 'nächstes Feld', it: 'prossima casella', ru: 'следующая клетка', uk: 'наступна клітинка', pl: 'następne pole', tr: 'sonraki kare', vi: 'ô tiếp theo', id: 'ubin berikutnya', zh: '下一格', ja: '次のマス', ko: '다음 타일' },
  'mines.gems': { en: 'gem(s)', es: 'gema(s)', pt: 'gema(s)', fr: 'gemme(s)', de: 'Edelstein(e)', it: 'gemma/e', ru: 'самоцвет(ов)', uk: 'самоцвіт(ів)', pl: 'klejnot(y)', tr: 'değerli taş', vi: 'đá quý', id: 'permata', zh: '宝石', ja: '宝石', ko: '보석' },
  'mines.minesLower': { en: 'mines', es: 'minas', pt: 'minas', fr: 'mines', de: 'Minen', it: 'mine', ru: 'мин', uk: 'мін', pl: 'min', tr: 'mayın', vi: 'mìn', id: 'ranjau', zh: '地雷', ja: '地雷', ko: '지뢰' },
  'mines.cashOut': { en: 'Cash out', es: 'Retirar', pt: 'Sacar', fr: 'Encaisser', de: 'Auszahlen', it: 'Incassa', ru: 'Забрать', uk: 'Забрати', pl: 'Wypłać', tr: 'Nakde çevir', vi: 'Rút tiền', id: 'Cairkan', zh: '兑现', ja: 'キャッシュアウト', ko: '캐시아웃' },
  'mines.stake': { en: 'Stake', es: 'Apuesta', pt: 'Aposta', fr: 'Mise', de: 'Einsatz', it: 'Puntata', ru: 'Ставка', uk: 'Ставка', pl: 'Stawka', tr: 'Bahis', vi: 'Cược', id: 'Taruhan', zh: '下注额', ja: '賭け金', ko: '베팅액' },
  'mines.mines': { en: 'Mines', es: 'Minas', pt: 'Minas', fr: 'Mines', de: 'Minen', it: 'Mine', ru: 'Мины', uk: 'Міни', pl: 'Miny', tr: 'Mayınlar', vi: 'Số mìn', id: 'Ranjau', zh: '地雷数', ja: '地雷', ko: '지뢰' },
  'mines.starting': { en: 'Starting…', es: 'Iniciando…', pt: 'Iniciando…', fr: 'Démarrage…', de: 'Startet…', it: 'Avvio…', ru: 'Запуск…', uk: 'Запуск…', pl: 'Uruchamianie…', tr: 'Başlatılıyor…', vi: 'Đang bắt đầu…', id: 'Memulai…', zh: '启动中…', ja: '開始中…', ko: '시작 중…' },
  'mines.bet': { en: 'Bet', es: 'Apostar', pt: 'Apostar', fr: 'Parier', de: 'Setzen', it: 'Scommetti', ru: 'Ставка', uk: 'Ставка', pl: 'Postaw', tr: 'Bahis Yap', vi: 'Đặt cược', id: 'Pasang', zh: '下注', ja: '賭ける', ko: '베팅' },
  'mines.latestGames': { en: 'Latest games', es: 'Últimas partidas', pt: 'Últimos jogos', fr: 'Dernières parties', de: 'Letzte Spiele', it: 'Ultime partite', ru: 'Последние игры', uk: 'Останні ігри', pl: 'Ostatnie gry', tr: 'Son oyunlar', vi: 'Ván gần đây', id: 'Permainan terbaru', zh: '最新对局', ja: '最新のゲーム', ko: '최근 게임' },
  'mines.multiplierCol': { en: 'Multiplier', es: 'Multiplicador', pt: 'Multiplicador', fr: 'Multiplicateur', de: 'Multiplikator', it: 'Moltiplicatore', ru: 'Множитель', uk: 'Множник', pl: 'Mnożnik', tr: 'Çarpan', vi: 'Hệ số', id: 'Pengganda', zh: '倍数', ja: '倍率', ko: '배율' },
  'mines.resultCol': { en: 'Result', es: 'Resultado', pt: 'Resultado', fr: 'Résultat', de: 'Ergebnis', it: 'Risultato', ru: 'Результат', uk: 'Результат', pl: 'Wynik', tr: 'Sonuç', vi: 'Kết quả', id: 'Hasil', zh: '结果', ja: '結果', ko: '결과' },
  'mines.noGames': { en: 'No games yet. Be the first.', es: 'Aún no hay partidas. Sé el primero.', pt: 'Ainda não há jogos. Seja o primeiro.', fr: 'Aucune partie pour le moment. Soyez le premier.', de: 'Noch keine Spiele. Sei der Erste.', it: 'Ancora nessuna partita. Sii il primo.', ru: 'Пока нет игр. Будьте первым.', uk: 'Ще немає ігор. Будьте першим.', pl: 'Brak gier. Bądź pierwszy.', tr: 'Henüz oyun yok. İlk sen ol.', vi: 'Chưa có ván nào. Hãy là người đầu tiên.', id: 'Belum ada permainan. Jadilah yang pertama.', zh: '暂无对局，快来第一个尝试吧。', ja: 'まだゲームがありません。最初のプレイヤーになろう。', ko: '아직 게임이 없어요. 첫 플레이어가 되어보세요.' },
  'mines.win': { en: 'Win', es: 'Gana', pt: 'Vitória', fr: 'Gagné', de: 'Gewonnen', it: 'Vinto', ru: 'Победа', uk: 'Перемога', pl: 'Wygrana', tr: 'Kazandı', vi: 'Thắng', id: 'Menang', zh: '获胜', ja: '勝利', ko: '승리' },
  'mines.bust': { en: 'Bust', es: 'Perdido', pt: 'Perdeu', fr: 'Perdu', de: 'Verloren', it: 'Perso', ru: 'Проигрыш', uk: 'Програш', pl: 'Przegrana', tr: 'Kaybetti', vi: 'Thua', id: 'Kalah', zh: '失败', ja: '失敗', ko: '패배' },
  'mines.errStart': { en: 'Could not start the game', es: 'No se pudo iniciar el juego', pt: 'Não foi possível iniciar o jogo', fr: 'Impossible de démarrer la partie', de: 'Spiel konnte nicht gestartet werden', it: 'Impossibile avviare la partita', ru: 'Не удалось начать игру', uk: 'Не вдалося почати гру', pl: 'Nie udało się rozpocząć gry', tr: 'Oyun başlatılamadı', vi: 'Không thể bắt đầu ván chơi', id: 'Gagal memulai permainan', zh: '无法开始游戏', ja: 'ゲームを開始できませんでした', ko: '게임을 시작할 수 없습니다' },
  'mines.errGeneric': { en: 'Something went wrong', es: 'Algo salió mal', pt: 'Algo deu errado', fr: 'Une erreur est survenue', de: 'Etwas ist schiefgelaufen', it: 'Qualcosa è andato storto', ru: 'Что-то пошло не так', uk: 'Щось пішло не так', pl: 'Coś poszło nie tak', tr: 'Bir şeyler yanlış gitti', vi: 'Đã có lỗi xảy ra', id: 'Terjadi kesalahan', zh: '出错了', ja: '問題が発生しました', ko: '문제가 발생했습니다' },
  'mines.errCashout': { en: 'Could not cash out', es: 'No se pudo retirar', pt: 'Não foi possível sacar', fr: "Impossible d'encaisser", de: 'Auszahlung fehlgeschlagen', it: 'Impossibile incassare', ru: 'Не удалось забрать выигрыш', uk: 'Не вдалося забрати виграш', pl: 'Nie udało się wypłacić', tr: 'Nakde çevrilemedi', vi: 'Không thể rút tiền', id: 'Gagal mencairkan', zh: '无法兑现', ja: 'キャッシュアウトできませんでした', ko: '캐시아웃할 수 없습니다' },
};

for (const [key, vals] of Object.entries(EXTRA)) {
  for (const code of Object.keys(STRINGS)) {
    STRINGS[code][key] = vals[code] ?? vals.en ?? key;
  }
}